### ISSUE TITLE
For "region-cloner" to speed up the removal of chunks.

### ISSUE THREAD

**Issue by flameSla** [mulark/factorio_benchmarking_mods#3] opened 2021-08-01 10:49 UTC
Delete chunks using the "Remove all entities" & "Fill with lab tiles" method from /editor

**Comment by mulark** [comment] 2021-08-04 02:01
Can you clarify a bit what you mean here? It doesn't remove chunks (It does delete entities on chunks in the paste area).

I also am not sure if we will want to set to checkerboard lab tiles in the pasted area. It does appear to at least be possible
https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.build_checkerboard

**Comment by flameSla** [comment] 2021-08-04 02:58
example: 
1) choose a medium-sized build for the copy, copy 10 times to the north
2) do not change anything, click the "copy" button again
the copy speed drops by about 2 times, I want to avoid this, I don't know how yet

I will write another example later (with saves)

**Comment by flameSla** [comment] 2021-08-04 06:49
savefile https://disk.yandex.ru/d/hCCu9L9Z4Z6t9g
copy settings
Left_top **-9984** **0**
Right_bottom **9984** **96**
Direction to copy **North** Number of copies **1**

1) Open the file in the game, click the "Start" button. 
15 minutes have passed, the copying process is still in progress. 
Killed the Factorio process.

2) Open the file in the game. 
run the command
```
/c local p=game.player p.surface.clone_area{source_area = {left_top = {-9984, 0}, right_bottom = {9984, 96}}, 
					destination_area = {left_top = {-9984, -96}, right_bottom = {9984, 0}}, 
					destination_surface = p.surface, 
					destination_force = p.force, 
					clone_tiles = true, 
					clone_entities = false, 
					clone_decoratives = false, 
					clear_destination_entities = true, 
					clear_destination_decoratives = true, 
					expand_map = true, 
					create_build_effect_smoke = false}
```
then click the "Start" button. 
It took 1.5 minutes for the copying process to complete.

**Comment by mulark** [comment] 2021-08-13 23:48
A big part of the issue is we have a ~N^2 complexity in the clear_paste_area.
```
        for key,found_ent in pairs (possible_entities_to_destroy) do
            if (found_ent.valid) then
                --TODO this is a hack for now
                if found_ent.type ~= "resource" then
                    for _,ent in pairs(entity_pool) do
                        if (found_ent == ent) then
                            --If any entity we find in the possible area to destroy entities is part of the set we intend to clone from, dont destroy that entity.
                            possible_entities_to_destroy[key] = nil
                        end
                    end
                end
            end
        end
```
I can fix this to be 2N.
It's also possible that clear_destination_entities is a faster than manually destroy()ing each entity.

**Comment by mulark** [comment] 2021-08-14 01:00
Appears to be resolved via https://github.com/mulark/factorio_benchmarking_mods/commit/77b0419742ecb8f84d912a23dbf0339cb221aad6
Thanks!

**Closed by mulark** 2021-08-14 01:00 UTC
